velodyne_convert_node:
    ros__parameters:
        calibration: 64e_s3-xiesc.yaml
        model: 64E
        min_range: 0.9
        max_range: 200.0
        view_direction: 0.0
        organize_cloud: true
